#!/bin/bash
# Original version (C) 2011 by jonasvp
# Modified version by danwerner

# Save this file as .git/hooks/pre-commit, make it executable, and it will
# thank you by saving you from common mistakes *before* deployment.

# Conflict markers
git diff --cached --diff-filter=ACMR | awk '/\+(<<<[<]<<<|>>>[>]>>>|===[=]===$)/ { exit 1 }'
CODE=$?
if [ "$CODE" != "0" ]; then
    echo "COMMIT ABORTED: Conflict markers found." >&2
    exit $CODE
fi
